import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import SidebarBody from './components/SidebarWithBody';
const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  home,
  login,
  children,
}: {
  children: React.ReactNode;
  home: React.ReactNode;
  login: React.ReactNode;
}) {
  const isLoggedIn = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarBody>
          {children}
          {isLoggedIn ? home : login}
        </SidebarBody>
      </body>
    </html>
  );
}
