// 'use client';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import SidebarBody from './components/SidebarWithBody';
// import {getSession} from '@/utils/lib';
const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  home,
  login,
  children,
}: {
  children: React.ReactNode;
  home: React.ReactNode;
  login: React.ReactNode;
}) {
  // const isLoggedIn = false;
  // const isLoggedIn = await getSession();
  // console.log('isLoggedIn', isLoggedIn);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarBody>{children}</SidebarBody>
      </body>
    </html>
  );
}
